// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

#nullable enable

namespace PlatzPilot.Resources.Strings;

using System;
using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
public class AppResources
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal AppResources()
    {
    }

    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan == null)
            {
                resourceMan = new ResourceManager("PlatzPilot.Resources.Strings.AppResources", typeof(AppResources).Assembly);
            }

            return resourceMan;
        }
    }

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string HomeTitle => ResourceManager.GetString("HomeTitle", resourceCulture) ?? string.Empty;
    public static string HomeTabLabel => ResourceManager.GetString("HomeTabLabel", resourceCulture) ?? string.Empty;
    public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", resourceCulture) ?? string.Empty;
    public static string NoResultsTitle => ResourceManager.GetString("NoResultsTitle", resourceCulture) ?? string.Empty;
    public static string NoResultsSubtitle => ResourceManager.GetString("NoResultsSubtitle", resourceCulture) ?? string.Empty;
    public static string FavoritesEmptyText => ResourceManager.GetString("FavoritesEmptyText", resourceCulture) ?? string.Empty;
    public static string OfflineBannerText => ResourceManager.GetString("OfflineBannerText", resourceCulture) ?? string.Empty;
    public static string ClosedLabel => ResourceManager.GetString("ClosedLabel", resourceCulture) ?? string.Empty;
    public static string ClosedStudentsLabel => ResourceManager.GetString("ClosedStudentsLabel", resourceCulture) ?? string.Empty;
    public static string ManualCountLabel => ResourceManager.GetString("ManualCountLabel", resourceCulture) ?? string.Empty;
    public static string AvailabilityFormat => ResourceManager.GetString("AvailabilityFormat", resourceCulture) ?? string.Empty;
    public static string OccupancyApproxPercent => ResourceManager.GetString("OccupancyApproxPercent", resourceCulture) ?? string.Empty;
    public static string NoCurrentInfoText => ResourceManager.GetString("NoCurrentInfoText", resourceCulture) ?? string.Empty;
    public static string DataStaleText => ResourceManager.GetString("DataStaleText", resourceCulture) ?? string.Empty;
    public static string RecommendationNoneText => ResourceManager.GetString("RecommendationNoneText", resourceCulture) ?? string.Empty;
    public static string RecommendationFormat => ResourceManager.GetString("RecommendationFormat", resourceCulture) ?? string.Empty;
    public static string PeakNoneText => ResourceManager.GetString("PeakNoneText", resourceCulture) ?? string.Empty;
    public static string PeakFormat => ResourceManager.GetString("PeakFormat", resourceCulture) ?? string.Empty;
    public static string QualityFormat => ResourceManager.GetString("QualityFormat", resourceCulture) ?? string.Empty;
    public static string QualityLow => ResourceManager.GetString("QualityLow", resourceCulture) ?? string.Empty;
    public static string QualityMedium => ResourceManager.GetString("QualityMedium", resourceCulture) ?? string.Empty;
    public static string QualityHigh => ResourceManager.GetString("QualityHigh", resourceCulture) ?? string.Empty;
    public static string PeakTrendFormat => ResourceManager.GetString("PeakTrendFormat", resourceCulture) ?? string.Empty;
    public static string PeakTrendEarlier => ResourceManager.GetString("PeakTrendEarlier", resourceCulture) ?? string.Empty;
    public static string PeakTrendLater => ResourceManager.GetString("PeakTrendLater", resourceCulture) ?? string.Empty;
    public static string PeakTrendFlat => ResourceManager.GetString("PeakTrendFlat", resourceCulture) ?? string.Empty;
    public static string MensaVirtualName => ResourceManager.GetString("MensaVirtualName", resourceCulture) ?? string.Empty;
    public static string MensaDisplayName => ResourceManager.GetString("MensaDisplayName", resourceCulture) ?? string.Empty;
    public static string MensaFluxFillingFastLabel => ResourceManager.GetString("MensaFluxFillingFastLabel", resourceCulture) ?? string.Empty;
    public static string MensaFluxEmptyingLabel => ResourceManager.GetString("MensaFluxEmptyingLabel", resourceCulture) ?? string.Empty;
    public static string CampusRadarLabel => ResourceManager.GetString("CampusRadarLabel", resourceCulture) ?? string.Empty;
    public static string FavoritesLabel => ResourceManager.GetString("FavoritesLabel", resourceCulture) ?? string.Empty;
    public static string SettingsLabel => ResourceManager.GetString("SettingsLabel", resourceCulture) ?? string.Empty;
    public static string FilterTitle => ResourceManager.GetString("FilterTitle", resourceCulture) ?? string.Empty;
    public static string FilterReset => ResourceManager.GetString("FilterReset", resourceCulture) ?? string.Empty;
    public static string WhenTitle => ResourceManager.GetString("WhenTitle", resourceCulture) ?? string.Empty;
    public static string WhenNow => ResourceManager.GetString("WhenNow", resourceCulture) ?? string.Empty;
    public static string WhenBefore => ResourceManager.GetString("WhenBefore", resourceCulture) ?? string.Empty;
    public static string RoomTypeTitle => ResourceManager.GetString("RoomTypeTitle", resourceCulture) ?? string.Empty;
    public static string RoomTypeGroup => ResourceManager.GetString("RoomTypeGroup", resourceCulture) ?? string.Empty;
    public static string RoomTypeSilent => ResourceManager.GetString("RoomTypeSilent", resourceCulture) ?? string.Empty;
    public static string RoomTypeNoReservation => ResourceManager.GetString("RoomTypeNoReservation", resourceCulture) ?? string.Empty;
    public static string EquipmentTitle => ResourceManager.GetString("EquipmentTitle", resourceCulture) ?? string.Empty;
    public static string EquipmentWifi => ResourceManager.GetString("EquipmentWifi", resourceCulture) ?? string.Empty;
    public static string EquipmentPower => ResourceManager.GetString("EquipmentPower", resourceCulture) ?? string.Empty;
    public static string EquipmentWhiteboard => ResourceManager.GetString("EquipmentWhiteboard", resourceCulture) ?? string.Empty;
    public static string OpeningHoursTitle => ResourceManager.GetString("OpeningHoursTitle", resourceCulture) ?? string.Empty;
    public static string SortTitle => ResourceManager.GetString("SortTitle", resourceCulture) ?? string.Empty;
    public static string SortByLabel => ResourceManager.GetString("SortByLabel", resourceCulture) ?? string.Empty;
    public static string ShowResultsFormat => ResourceManager.GetString("ShowResultsFormat", resourceCulture) ?? string.Empty;
    public static string MinimumOpenHoursFormat => ResourceManager.GetString("MinimumOpenHoursFormat", resourceCulture) ?? string.Empty;
    public static string OpenMapLabel => ResourceManager.GetString("OpenMapLabel", resourceCulture) ?? string.Empty;
    public static string OpenWebsiteLabel => ResourceManager.GetString("OpenWebsiteLabel", resourceCulture) ?? string.Empty;
    public static string BuildingLabel => ResourceManager.GetString("BuildingLabel", resourceCulture) ?? string.Empty;
    public static string BuildingFormat => ResourceManager.GetString("BuildingFormat", resourceCulture) ?? string.Empty;
    public static string SingleLocationSubtitle => ResourceManager.GetString("SingleLocationSubtitle", resourceCulture) ?? string.Empty;
    public static string GroupedLocationSubtitleFormat => ResourceManager.GetString("GroupedLocationSubtitleFormat", resourceCulture) ?? string.Empty;
    public static string OpeningHoursLabel => ResourceManager.GetString("OpeningHoursLabel", resourceCulture) ?? string.Empty;
    public static string LastCountLabel => ResourceManager.GetString("LastCountLabel", resourceCulture) ?? string.Empty;
    public static string RoomsInBuildingLabel => ResourceManager.GetString("RoomsInBuildingLabel", resourceCulture) ?? string.Empty;
    public static string HomeAvailabilitySubFormat => ResourceManager.GetString("HomeAvailabilitySubFormat", resourceCulture) ?? string.Empty;
    public static string LastUpdatedFormat => ResourceManager.GetString("LastUpdatedFormat", resourceCulture) ?? string.Empty;
    public static string LastUpdatedUnknownText => ResourceManager.GetString("LastUpdatedUnknownText", resourceCulture) ?? string.Empty;
    public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture) ?? string.Empty;
    public static string SettingsDesignLabel => ResourceManager.GetString("SettingsDesignLabel", resourceCulture) ?? string.Empty;
    public static string SettingsDisplayTitle => ResourceManager.GetString("SettingsDisplayTitle", resourceCulture) ?? string.Empty;
    public static string SettingsFeedbackTitle => ResourceManager.GetString("SettingsFeedbackTitle", resourceCulture) ?? string.Empty;
    public static string SettingsInfoTitle => ResourceManager.GetString("SettingsInfoTitle", resourceCulture) ?? string.Empty;
    public static string SettingsHapticLabel => ResourceManager.GetString("SettingsHapticLabel", resourceCulture) ?? string.Empty;
    public static string HideClosedLocationsLabel => ResourceManager.GetString("HideClosedLocationsLabel", resourceCulture) ?? string.Empty;
    public static string SettingsVersionFormat => ResourceManager.GetString("SettingsVersionFormat", resourceCulture) ?? string.Empty;
    public static string SettingsDisclaimer => ResourceManager.GetString("SettingsDisclaimer", resourceCulture) ?? string.Empty;
    public static string AboutButtonLabel => ResourceManager.GetString("AboutButtonLabel", resourceCulture) ?? string.Empty;
    public static string AboutTitle => ResourceManager.GetString("AboutTitle", resourceCulture) ?? string.Empty;
    public static string AboutCloseLabel => ResourceManager.GetString("AboutCloseLabel", resourceCulture) ?? string.Empty;
    public static string GithubLabel => ResourceManager.GetString("GithubLabel", resourceCulture) ?? string.Empty;
    public static string ImpressumLabel => ResourceManager.GetString("ImpressumLabel", resourceCulture) ?? string.Empty;
    public static string PrivacyLabel => ResourceManager.GetString("PrivacyLabel", resourceCulture) ?? string.Empty;
    public static string LicensesLabel => ResourceManager.GetString("LicensesLabel", resourceCulture) ?? string.Empty;
    public static string LicensesTitle => ResourceManager.GetString("LicensesTitle", resourceCulture) ?? string.Empty;
    public static string LicensesText => ResourceManager.GetString("LicensesText", resourceCulture) ?? string.Empty;
    public static string ColorBlindModeLabel => ResourceManager.GetString("ColorBlindModeLabel", resourceCulture) ?? string.Empty;
    public static string CampusSouthOnlyLabel => ResourceManager.GetString("CampusSouthOnlyLabel", resourceCulture) ?? string.Empty;
    public static string BackGlyph => ResourceManager.GetString("BackGlyph", resourceCulture) ?? string.Empty;
    public static string OkButtonLabel => ResourceManager.GetString("OkButtonLabel", resourceCulture) ?? string.Empty;
    public static string FavoriteIconFilled => ResourceManager.GetString("FavoriteIconFilled", resourceCulture) ?? string.Empty;
    public static string FavoriteIconOutline => ResourceManager.GetString("FavoriteIconOutline", resourceCulture) ?? string.Empty;
    public static string LevelFormat => ResourceManager.GetString("LevelFormat", resourceCulture) ?? string.Empty;
    public static string RoomFormat => ResourceManager.GetString("RoomFormat", resourceCulture) ?? string.Empty;
    public static string BuildingUnknownText => ResourceManager.GetString("BuildingUnknownText", resourceCulture) ?? string.Empty;
    public static string ChartLabel6Hours => ResourceManager.GetString("ChartLabel6Hours", resourceCulture) ?? string.Empty;
    public static string ChartLabel12Hours => ResourceManager.GetString("ChartLabel12Hours", resourceCulture) ?? string.Empty;
    public static string ChartLabel18Hours => ResourceManager.GetString("ChartLabel18Hours", resourceCulture) ?? string.Empty;
    public static string ErrorMessage_NoConnection => ResourceManager.GetString("ErrorMessage_NoConnection", resourceCulture) ?? string.Empty;
    public static string BuildingName_BadischeLandesbibliothek => ResourceManager.GetString("BuildingName_BadischeLandesbibliothek", resourceCulture) ?? string.Empty;
    public static string LanguageLabel => ResourceManager.GetString("LanguageLabel", resourceCulture) ?? string.Empty;
    public static string LanguageSelectTitle => ResourceManager.GetString("LanguageSelectTitle", resourceCulture) ?? string.Empty;
    public static string LanguageOptionGerman => ResourceManager.GetString("LanguageOptionGerman", resourceCulture) ?? string.Empty;
    public static string LanguageOptionEnglish => ResourceManager.GetString("LanguageOptionEnglish", resourceCulture) ?? string.Empty;
    public static string LanguageOptionCancel => ResourceManager.GetString("LanguageOptionCancel", resourceCulture) ?? string.Empty;
}

#nullable restore
